baseurl: "/core"
layouts_dir: ".shared/_layouts"
includes_dir: ".shared/_includes"

external_css:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/default.min.css

external_js:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js